### ISSUE TITLE
"Get Decision Definitions" Result table broken (missing type cell for versionTagLike)

### ISSUE THREAD

**Issue by pjungermann** [camunda/camunda-docs-manual#192]
https://docs.camunda.org/manual/7.9/reference/rest/decision-definition/get-query/#result

Row with versionTagLike misses the middle cell for the type

**Comment by yanavasileva** [comment]
Hi Patrick,

Gut catch, thanks.
It is fixed now with (0ea2517).
Are you interested in providing pull requests in the future?

Best regards,
Yana
