### ISSUE TITLE
"Post Process Variable (Binary)" parameters is not a headline but paragraph

### ISSUE THREAD

**Issue by pjungermann** [camunda/camunda-docs-manual#193]
https://docs.camunda.org/manual/7.9/reference/rest/process-instance/variables/post-variable-binary/

`<p>parameters</p>`

instead of the correct

`<h1 id="parameters">Parameters<a href="#parameters" class="content-anchor glyphicon glyphicon-link"></a></h1>`

**Comment by yanavasileva** [comment]
Hi Patrick,

Thanks for pointing this.
Fix with (0ea2517).
Are you interested in providing pull requests in the future?

Best regards,
Yana
