### ISSUE TITLE
Incorrect REST URL for Set Job Retries Async (POST) on Job resources list

### ISSUE THREAD

**Issue by codygulley** [camunda/camunda-docs-manual#208]
[https://docs.camunda.org/manual/latest/reference/rest/job/](https://docs.camunda.org/manual/latest/reference/rest/job/)
 has the url for Set Job Retries Async (POST) as POST /**process-instance**/retries but it should be POST /**job**/retries  as referred to when you click on that specific resource . ([https://docs.camunda.org/manual/latest/reference/rest/job/post-set-job-retries/](https://docs.camunda.org/manual/latest/reference/rest/job/post-set-job-retries/)). 

![screen shot 2019-01-18 at 11 56 39 am](https://user-images.githubusercontent.com/8097956/51407115-355d9000-1b18-11e9-9d16-02b7a4e97c86.png)
![screen shot 2019-01-18 at 11 57 05 am](https://user-images.githubusercontent.com/8097956/51407119-37275380-1b18-11e9-894f-81faa0e01b04.png)

**Comment by codygulley** [comment]
I would love to create a pull request for this - but I don't have permission to create a branch. 

The problem lies in  content/reference/rest/job/post-set-job-retries.md  on line 10.

**Comment by tmetzke** [comment]
Hi Cody,

thank you very much for the remarks.

We are very happy to hear that you want to contribute.
Best way to create pull requests for this repository is by forking it from master and creating the request from that fork as described [here](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).

We'll then close the issue when your pull request is merged.
Looking forward to your contributions!

Best regards
Tobias

**Comment by codygulley** [comment]
@tmetzke Thanks for the reply! I will use this method going forward. 
 I have opened a PR with a fix for this issue.
