### ISSUE TITLE
Contradicting METHOD for Execute Job REST API documentation

### ISSUE THREAD

**Issue by codygulley** [camunda/camunda-docs-manual#209]
![screen shot 2019-01-18 at 12 28 55 pm](https://user-images.githubusercontent.com/8097956/51408685-d2bac300-1b1c-11e9-96a6-054ca705707f.png)

Method says POST but example says PUT.

**Comment by tmetzke** [comment]
Hi Cody,

thank you very much for spotting this!
The example was wrong there.

I changed it, see https://github.com/camunda/camunda-docs-manual/commit/6ab0db9bb81550e7dbd63ad00f593616ef74ba57.

Best regards
Tobias
