### ISSUE TITLE
List all available archetype in docs

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-docs-manual#219]
https://docs.camunda.org/manual/7.10/user-guide/process-applications/maven-archetypes/

is outdated. It should also include the Spring Boot and the Engine plugin archetypes.

I'd edit it myself, but I'm afraid I won't find the time in the next weeks.

**Comment by yanavasileva** [comment]
Created https://app.camunda.com/jira/browse/CAM-9812 for it.
