### ISSUE TITLE
Active BPM Platform Tab causes hiding of new Security Tab

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-docs-manual#225]
See Screenshots. Is that intended? It's probably a quick fix, but I don't know how to do that :)

![Screenshot 2019-03-29 at 15 11 35](https://user-images.githubusercontent.com/17595149/55238715-7ae3bb00-5235-11e9-920e-5b27e057d5f5.png)
![Screenshot 2019-03-29 at 15 11 41](https://user-images.githubusercontent.com/17595149/55238718-7b7c5180-5235-11e9-9073-ea2b6a4d4610.png)

**Comment by yanavasileva** [comment]
Hi @benhoffmann ,

Does the issue still persist?
What are the steps to reproduce?

Best regards,
Yana

**Comment by benhoffmann** [comment]
Seems to be working alright now. I'm closing this issue
