### ISSUE TITLE
Process businessKey is no longer unique for a process instance

### ISSUE THREAD

**Issue by spaungam** [camunda/camunda-docs-manual#242]
There are a few Camunda forum postings and related references where it's mentioned that a businessKey was at some point in time required to be unique, but is no longer required to be unique.  Sample discussion:

https://forum.camunda.org/t/storing-null-value-for-process-task-variables/10129/2
Screen Shot 2019-06-26 at 1.36.54 AM.png

Meanwhile, the api doc for [post-start-process-instance.md](content/reference/rest/process-definition/post-start-process-instance.md) states:

`The business key the process instance is to be initialized with. The business key uniquely identifies the process instance in the context of the given process definition.`

**Comment by yanavasileva** [comment]
Hi @spaungam,

Are you interested in providing a pull request to improve the docs?
Keep in mind that the official bug tracking system is [Jira](https://app.camunda.com/jira/secure/CreateIssue!default.jspa). In the future, I recommend you to create a ticket there.
Hereby I am closing the issue.

Best,
Yana
