### ISSUE TITLE
Unable to configure engine to register user's tenant to instantiated process 

### ISSUE THREAD

**Issue by patozgg** [camunda/camunda-docs-manual#244]
I tried following the documentation found here https://github.com/camunda/camunda-docs-manual/blob/7.11/content/user-guide/process-engine/multi-tenancy.md#instantiate-a-shared-definition  to try and insantiate a process and register the user's tenant to it. Is the documentation complete?  I tried this in my own Springboot + Camunda project.

**Comment by yanavasileva** [comment]
Hi Patricio,

It is better to create Jira tickets as our official tracking tool when something is wrong with the documentation.
In the described case, I think it is a matter of misconfiguration and the documentation is ok.
If you want you can send me your project and I will check.
Hereby I close the issue.

Best regards,
Yana
