### ISSUE TITLE
Error in MVN version for v7.11 Spring Boot Integration

### ISSUE THREAD

**Issue by cdr72ex** [camunda/camunda-docs-manual#280]
https://docs.camunda.org/manual/7.11/user-guide/spring-boot-integration/
The dependency is incorrect in stating it should be 3.3.5. That version does not exist. It should be 3.3.4
`<dependency>
  <groupId>org.camunda.bpm.springboot</groupId>
  <artifactId>camunda-bpm-spring-boot-starter</artifactId>
  <version>3.3.5</version>
</dependency>`

Should be:
`<dependency>
  <groupId>org.camunda.bpm.springboot</groupId>
  <artifactId>camunda-bpm-spring-boot-starter</artifactId>
  <version>3.3.4</version>
</dependency>`

**Comment by yanavasileva** [comment]
Fixed with PR #281
