### ISSUE TITLE
Dead link to Cron trigger documentation.

### ISSUE THREAD

**Issue by l1n3n01z** [camunda/camunda-docs-manual#291]
The link from the [Timer Events page](https://docs.camunda.org/manual/latest/reference/bpmn20/events/timer-events/) to the Quartz Scheduler Cron Trigger documentation is dead. A link that currently works is http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/tutorial-lesson-06.html

**Comment by yanavasileva** [comment]
Resolved in #434.
