### ISSUE TITLE
Error throwing event exists?

### ISSUE THREAD

**Issue by leolux** [camunda/camunda-docs-manual#79]
Regarding the first picture in https://docs.camunda.org/manual/7.3/api-references/bpmn20/#events-error-events-error-start-event

The picture there contains an error throwing event as well as an error start event. But camunda does not seem to support any error throwing event (nor does BPMN 2.0 ?). The list of BPMN coverage does not even have an entry at this place [1]

[1] https://docs.camunda.org/manual/7.3/api-references/bpmn20/

**Comment by ThorbenLindhauer** [comment]
Hi @leolux,

Both BPMN 2.0 and Camunda support BPMN error end events. In the overview, there is in fact an error end event (see right-most column). However, no error intermediate throwing event exists.

Cheers,
Thorben

**Comment by leolux** [comment]
Alright, got it!

Somehow I mixed up the notation semantic of the end event with the intermediate throw event which was my mistake in the first place.

Thank you!
