### ISSUE TITLE
Ensure matching version between Camunda Spin and the process engine

### ISSUE THREAD

**Issue by leolux** [camunda/camunda-docs-manual#82]
The documentation says "ensure that you use the Camunda Spin version matching your process engine version" [1]. But the version of my camunda engine is 7.4.0 and the version of camunda spin is 1.3.0 [2] . How should the versions match 7.4.0 and which version of the artifact camunda-spin-bom should be used?

[1] https://docs.camunda.org/manual/7.3/api-references/spin/#overview-introduction
[2] http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.camunda.spin%22

**Comment by hawky-4s-** [comment]
Hi Leolux,

When you follow the link in the hint with the blue background in your first reference, it leads to the [Camunda Bom](https://docs.camunda.org/get-started/apache-maven/#community-edition) which you should import when you use the Process Engine together with other Camunda stuff as stated in the hint. The Camunda Bom sets the correct versions for Spin etc. accordingly to the Camunda Version you are using. Eg. Camunda Bom 7.4.0 will import Spin 1.2.0, while Camunda Bom 7.5.0 will define Spin with the version 1.3.0.

**Comment by leolux** [comment]
Thanks hawky!  You solved my cofusion about this. 
So when Camunda Bom is already imported there is no need to import Camunda Spin Bom.
