### ISSUE TITLE
Search ignores Maven Archetypes

### ISSUE THREAD

**Issue by falko** [camunda/camunda-docs-manual#84]
We have a page called [Maven Project Templates (Archetypes)](https://docs.camunda.org/manual/7.5/user-guide/process-applications/maven-archetypes/), but it doesn't show up in the search when using any combination of words from the page title, e.g.:

- Maven
- Project Templates
- Archetypes

The search results even show all pages that reference the archetype page. When I tell people about the archetypes, I frequently tell them to search for it on docs.camunda.org, but they don't find them.

Could this be a general issue with the search that e.g. page titles are not considered for searching?

**Comment by meyerdan** [comment]
I do not know. We use google custom site search which is a balckbox.
