### ISSUE TITLE
Writing Standard for writing links/Href content?

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-docs-manual#89]
Trying to make some updates to the docs, and looking for what your standard on writing links/hrefs?

There seems to be two different usages:
1. Where there is a standard markdown href with a full link using Camunda.org domain
2. Where you use a special relative link format.  

What are the scenarios for each use case?

Example: https://github.com/camunda/camunda-docs-manual/blob/7.5/content/reference/bpmn20/subprocesses/embedded-subprocess.md

Where there is the links in the table of Camunda Extensions header and the links in the additional resources.

**Comment by meyerdan** [comment]
Hi Stephen,

* Links *within* the docs manual are relative
* Links to external content (like camunda.org) are absolute URLs.

Does that answer your question?

Best Regards,
Daniel
