### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by felixlinker** [camunda/camunda-docs-manual#99]
The link to Job Prioritization in this segment is broken:

https://github.com/camunda/camunda-docs-manual/blob/7.5/content/reference/bpmn20/custom-extensions/extension-attributes.md#jobpriority

**Comment by mburke84** [comment]
Hi @felixlinker 
Thanks for reaching out to us with this. This has been fixed with the following commit:
https://github.com/camunda/camunda-docs-manual/commit/c5810ff729cffe9f24a89662a51248422c907752

Thanks and best regards
